server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/accounts/**

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customers/**

            - id: credit-service
              uri: lb://credit-service
              predicates:
                - Path=/credits/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost

app:
  security:
    user:
      username: admin
      password: admin123

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 3600000